### PR TITLE
TextUnmarshaler interface support

### LINKED ISSUE #20: Support Text(Un)Marshaler methods.

### PR DESCRIPTION
**Pull request by rafaeljusto**
Automatically convert data to a type that implements the TextUnmarshaler interface.

Resolves #20

### CODE REVIEW

**Comment by rafaeljusto** [comment]
As the encoding package just appeared in Go 1.2, older versions are not going to support this patch.
http://tip.golang.org/doc/go1.2#encoding

**Comment by kisielk** [comment]
Thanks, I'll have a detailed look at it next week.

**Comment by rafaeljusto** [comment]
I added an Error attribute to the ConversionError type to store a possible low level error from the UnmarshalText function. This can be useful to understand what went wrong in the conversion.

**Comment by kisielk** [comment]
Thanks a lot. Sorry for taking so long to get to this :)

**Pull request merged**
