### PR TITLE
[Reopen] Support custom converter from struct field names to form fields (callback)

### PR DESCRIPTION
**Pull request by eshamster**
Fixes #54, #55

I reopen the pull request #55 that adds custom field name mapper. I changed the followings, but others are same to the original pull request. 

1. Merge master branch and resolve conflicts.
2. Rename type and function names according to the following comments.
    - https://github.com/gorilla/schema/pull/55#discussion_r53386801
    - https://github.com/gorilla/schema/pull/55#discussion_r53386803

### CODE REVIEW

**Comment by eshamster** [comment]
Hi @elithrar, could you see this PR?

**Comment by eshamster** [comment]
Hi @elithrar, sorry to bother you again.
Could you see the PR if you have a time?

**Comment by elithrar** [comment]
I will take a look this weekend.

**Comment by eshamster** [comment]
Thanks!

**Pull request closed without merging**
