### PR TITLE
add: "required" tag option support

### PR DESCRIPTION
**Pull request by kuangchanglang**
I think this issue is useful when parsing HTTP request parameters, looks like java spring "@Required" annotation.

### CODE REVIEW

**Comment by kisielk** [comment]
It seems reasonable to me. It doesn't seem to affect backwards compatibility... I'd like to see some tests for behaviour of required fields of other types such as numeric types as well. (eg: what happens when there is an empty string for a required int?).

**Comment by kuangchanglang** [comment]
Hi @kisielk , that case exposes the problem. I thought empty string for int type should fail when converting, but it turns out no errors.
I have added codes to fix it, please review once more.

**Comment by kisielk** [comment]
LGTM. @elithrar want to give this another set of eyes?

**Comment by elithrar** [comment]
LGTM.

**Comment by elithrar** [comment]
Thanks @kuangchanglang!

**Comment by AlekSi** [comment]
Why is it not documented?

**Pull request merged**
