### PR TITLE
Fix omitempty for encoding

### LINKED ISSUE #88: Add support on omitempty for all types
Hello,

I expected this behaviour which match `encoding/json` package.

Example: https://play.golang.org/p/o6IiMmNMK9

I wrote below the test to match the behaviour above but it fails.

The unit test:

```go

type E5 struct {
	F01 int     `schema:"f01,omitempty"`
	F02 string  `schema:"f02,omitempty"`
	F03 *string `schema:"f03,omitempty"`
	F04 *int8   `schema:"f04,omitempty"`
	F05 float64 `schema:"f05,omitempty"`
}

func TestEncoderWithOmitempty(t *testing.T) {
	vals := map[string][]string{}

	s := E5{}

	encoder := NewEncoder()
	encoder.Encode(&s, vals)

	valNotExists(t, "f01", vals)
	valNotExists(t, "f02", vals)
	valNotExists(t, "f03", vals)
	valNotExists(t, "f04", vals)
	valNotExists(t, "f05", vals)
}
```

Here is the trace:

```
Running tool: /usr/local/bin/go test -timeout 30s -tags  -run ^TestEncoderWithOmitempty$

--- FAIL: TestEncoderWithOmitempty (0.00s)
	/Users/aetcheverry/Projects/Go/src/github.com/gorilla/schema/encoder_test.go:273: Key not ommited. Expected: empty; got: 0.
	/Users/aetcheverry/Projects/Go/src/github.com/gorilla/schema/encoder_test.go:273: Key not ommited. Expected: empty; got: null.
	/Users/aetcheverry/Projects/Go/src/github.com/gorilla/schema/encoder_test.go:273: Key not ommited. Expected: empty; got: null.
	/Users/aetcheverry/Projects/Go/src/github.com/gorilla/schema/encoder_test.go:273: Key not ommited. Expected: empty; got: 0.000000.
FAIL
exit status 1
FAIL	github.com/gorilla/schema	0.005s
Error: Tests failed.
```

Thanks for your help. 😃

### PR DESCRIPTION
**Pull request by frozzare**
This will fix #88. Also added the unit test that was provided in the issue. Don't seems to break anything existing.

### CODE REVIEW

**Comment by kisielk** [comment]
Shouldn't the test also check that the fields are encoded if they are not empty?

**Comment by frozzare** [comment]
Completely forgot about it. Added a new commit that check for empty value and tests with both a empty and struct with values.

**Comment by elithrar** [comment]
@kisielk for second eyeball, but otherwise LGTM. Thanks for this @frozzare!

**Comment by kisielk** [comment]
The `reflect` API makes my brain hurt, but LGTM :)

**Pull request merged**
