### PR TITLE
Make registered converters take priority over TextUnmarshaler.

### PR DESCRIPTION
**Pull request by kisielk**
Fixes a bug in #84

### CODE REVIEW

**Comment by kisielk** [comment]
@HasMatthew @Azuka can you take a look this?

**Comment by Azuka** [comment]
I'd defer to @HasMatthew, but looks good.

**Comment by kisielk** [comment]
Ok, will merge once @HasMatthew confirms this fixes his bug.

**Comment by HasMatthew** [comment]
I've confirmed this PR fixes my use case. 👍

**Comment by kisielk** [comment]
Excellent :)

**Pull request merged**
